name = "DocumenterGitHubActionsExample"
uuid = "6a5b6cfc-4815-472e-98cb-d21c1850ccb7"
authors = ["Morten Piibeleht <morten.piibeleht@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
